site_name: pwninit Documentation
site_url: https://pwninit.0xb0tm4n.org

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: bash
          class: highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src] 

nav:
  - Home:
      - Introduction: index.md
      - Plugins: plugins.md
  - Pwninit:
    - Overwiew: pwninit/index.md
    - IOContext: pwninit/io.md
    - PwnContext: pwninit/pwncontext.md
    - Plugins: pwninit/plugins.md
    - Utils: pwninit/utils.md
